### ISSUE TITLE
Adding Relationship Metabox To Existing Metabox

### ISSUE THREAD

**Issue by davidatkadpro** [wpmetabox/meta-box#1262] opened 2018-08-16 02:08 UTC
I recently had an issue where I wanted to add the relationship metabox to an existing metabox.

The problem with this is currently there is no relationship field, so it's not really possible to add it.

But....

There is the MB_Relationships_API, that gives you the ability to Has, Add and Delete relationships.

So I have built a crude workaround that works with multiple relationships to a post.
It is actioned on the save_post action and uses the "[post](https://docs.metabox.io/fields/post/)" field in the metabox. 

Note: This does not work if your post field is nested in a group as the group's id will harbour the post field id. To get around this, I would suggest running a loop through the keys of the group until you find the post field id.

The three main required parameters are:

1. your relationship id.
2. your post field id within the metabox.
3. your from posts post type.

```
static public function init(){
	add_action( 'save_post', __CLASS__ . '::check_relationship', 20, 1);
}
static public function check_relationship($to_id){
	// dont run on auto save.
        if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
                return;		
        }
        // dont run if in trash.
	if('trash' === get_post_status( $to_id )){
		return;	
	}
	// these are the parameters required to perform the API requests.
	$rel_id   		= 'your_relationship_id';
	$post_field_id 	= 'your_post_field_id';
	$from_post_type = 'your_from_post_type';
	// this is used to get the post meta from the current saved post.
	$post_from_ids = get_post_meta($to_id, $post_field_id, false );
	// this checks if there was any linked posts returned from the current post meta, if none, set $post_from_ids as empty array.
	$post_from_ids ?: $post_from_ids = [];
	// get relationships with the current post
	$rel_from_ids = self::get_relationship($to_id, $rel_id, $from_post_type );
	// if there are any relationships that are not in the current post meta, remove them.
	if($rel_from_ids) {
		foreach ($rel_from_ids as $rel_from_id) {
			if (!in_array($rel_from_id, $post_from_ids)) {
				MB_Relationships_API::delete($rel_from_id, $to_id, $rel_id );
			}
		}			
	} 
	// add all the current post meta ids to the relationships table.
	if($post_from_ids) {	
		foreach ($post_from_ids as $post_from_id) {
			MB_Relationships_API::add( $post_from_id, $to_id, $rel_id );
		}
	} 
}
static private function get_relationship($to_id, $rel_id, $from_post_type ){
	// add your post type for the get_posts to check against with your current saved post.
	$args = array(
	    'post_type' => $from_post_type,
	    'posts_per_page'=>-1, 
	);
	$from_posts = get_posts( $args );
	$rel_from_ids = [];
	// loop through all the posts and use the MB_Relationships_API::has to check each against the current saved post.
	// If it matchs return with the matched post id, else return false as there is no relationship to be deleted.
	foreach ($from_posts as $from_post) {
		$rel_from_id = $from_post->ID;
		$has_connection = MB_Relationships_API::has($rel_from_id, $to_id, $rel_id);
		if($has_connection) {
			$rel_from_ids[] = $rel_from_id;
		}
	}
	if($rel_from_ids) {
		return $rel_from_ids;
	} else {
		return false;
	}
}
```
I have tried to make the parameter naming as easy to follow as posbile, but if there are any questions or suggestions please let me know.

**Comment by rilwis** [comment] 2018-08-16 08:55
@davidatkadpro Thanks a lot for your contribution. I think it's really useful for people who is looking for a similar solution. Would you mind porting it into a tutorial on Meta Box's blog?

**Comment by davidatkadpro** [comment] 2018-08-16 11:19
@rilwis most definitely, I have also since found a clean way of finding keys or values in multidimensional arrays really easily, comes in handy when using groups nested in other groups too.

**Comment by rilwis** [comment] 2018-08-18 08:26
Let me close this issue as it's not a bug. @davidatkadpro : please drop me an email via [Contact](https://metabox.io/contact/) regarding the blog post. Thanks a lot!

**Closed by rilwis** 2018-08-18 08:26 UTC
